---

- name: Install zsh
  pacman:
    name: zsh
    state: latest

- name: Clone oh-my-zsh
  git:
    repo: "{{ github }}robbyrussell/oh-my-zsh.git"
    dest: "{{ omzsh_dir }}"
    accept_hostkey: yes
  become: no

- name: Install oh-my-zsh
  shell: "{{ omzsh_dir }}/tools/install.sh"
  register: result
  changed_when: "'You already have Oh My Zsh installed' not in result.stdout"
  become: no

- name: Cloninig custom plugins
  git:
    repo: "{{ github }}{{ item.value }}/{{ item.key }}.git"
    dest: "{{ omzsh_plugins_dir }}/{{ item.key }}"
    accept_hostkey: yes
  with_dict:
    "{{ omzsh_plugins }}"
  become: no

- name: Clone pure theme
  git:
    repo: "{{ github }}sindresorhus/pure.git"
    dest: "{{ omzsh_themes_dir }}/pure"
    accept_hostkey: yes
  become: no

- name: Symlink pure theme files
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: '{{ omzsh_themes_dir }}/pure/async.zsh' , dest: '{{ omzsh_custom_dir }}/async.zsh' }
    - { src: '{{ omzsh_themes_dir }}/pure/pure.zsh' , dest: '{{ omzsh_themes_dir }}/pure.zsh-theme' }
  become: no

- name: Check for original .zshrc
  stat:
    path: "{{ user.home }}/.zshrc"
  register: stat_zshrc

- name: Back up .zshrc file
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: ~/.zshrc.bak
  become: no
  when: stat_zshrc.stat.exists

- name: Create .zshrc from template
  template:
    src: .zshrc.j2
    dest: "{{ user.home }}/.zshrc"
  become: no

- name: Set zsh as default shell
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh
