---

- name: Install zsh
  apt:
    name: zsh
    state: latest
  become: yes

- name: Clone oh-my-zsh
  git:
    repo: "{{ github }}/robbyrussell/oh-my-zsh.git"
    dest: "{{ omzsh_dir }}"
    accept_hostkey: yes

- name: Cloninig custom plugins
  git:
    repo: "{{ github }}/{{ item.value }}/{{ item.key }}.git"
    dest: "{{ omzsh_plugins_dir }}/{{ item.key }}"
    accept_hostkey: yes
  with_dict:
    "{{ omzsh_plugins }}"

- name: Clone powerlevel10k theme
  git:
    repo: "{{ github }}/romkatv/powerlevel10k.git"
    dest: "{{ omzsh_themes_dir }}/powerlevel10k"
    accept_hostkey: yes

- name: Check for original .zshrc
  stat:
    path: "{{ user.home }}/.zshrc"
  register: stat_zshrc

- name: Back up .zshrc file
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: ~/.zshrc.bak
  when: stat_zshrc.stat.exists

- name: Create .zshrc from template
  template:
    src: .zshrc.j2
    dest: "{{ user.home }}/.zshrc"

- name: Set zsh as default shell
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh
  become: yes
