---

- name: Install zsh libs
  pacman:
    name: zsh
    state: latest
- name: Install oh-my-zsh
  aur:
    name: oh-my-zsh-git
    user: "{{ user.name }}"
  tags:
    - aur

- name: Clone Base16 repo
  git:
    repo: "{{ github }}chriskempson/base16-shell.git"
    dest: "{{ user.home }}/.config/base16-shell"
    accept_hostkey: yes
  become: no

- name: Clone pure theme
  git:
    repo: "{{ github }}sindresorhus/pure.git"
    dest: "{{ omzsh_themes_dir }}/pure"
    accept_hostkey: yes
  become: no

- name: Symlink pure theme files
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  become: no
  with_items:
    - { src: '{{ omzsh_themes_dir }}/pure/async.zsh' , dest: '{{ omzsh_custom_dir }}/async.zsh' }
    - { src: '{{ omzsh_themes_dir }}/pure/pure.zsh' , dest: '{{ omzsh_themes_dir }}/pure.zsh-theme' }

- name: Clone custom plugins
  git:
    repo: "{{ github }}zsh-users/{{ item }}.git"
    dest: "{{ omzsh_plugins_dir }}/{{ item }}"
    accept_hostkey: yes
  become: no
  with_items:
    - "zsh-syntax-highlighting"
    - "zsh-autosuggestions"
    - "zsh-completions"

- name: Set zsh as default shell
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh
