---

- name: Install Visual Studio Code
  snap:
    name: vscode
    classic: yes

- name: Install extensions
  shell: "/snap/bin/code --install-extension {{ item }}"
  with_items:
    - alexkrechik.cucumberautocomplete
    - codezombiech.gitignore
    - DavidAnson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - eg2.tslint
    - formulahendry.code-runner
    - k--kato.intellij-idea-keybindings
    - mike-co.import-sorter
    - PeterJausovec.vscode-docker
    - plievone.vscode-template-literal-editor
    - rebornix.ruby
    - redhat.vscode-yaml
    - robertohuertasm.vscode-icons
    - samverschueren.final-newline
    - vscoss.vscode-ansible
    - wholroyd.jinja
    - trinm1709.dracula-theme-from-intellij
  register: result
  become: no
  changed_when: "'is already installed' not in result.stdout"
