---

- name: Install Visual Studio Code
  aur:
    name: visual-studio-code-bin
    use: makepkg
    skip_installed: yes
  become: no

- name: Install extensions
  shell: "code --install-extension {{ item }}"
  with_items:
    - alexkrechik.cucumberautocomplete
    - bung87.vscode-gemfile
    - bungcip.better-toml
    - castwide.solargraph
    - codezombiech.gitignore
    - DavidAnson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - eg2.tslint
    - fatihacet.gitlab-workflow
    - formulahendry.code-runner
    - gencer.html-slim-scss-css-class-completion
    - groksrc.ruby
    - k--kato.intellij-idea-keybindings
    - kaiwood.endwise
    - kumar-harsh.graphql-for-vscode
    - mike-co.import-sorter
    - ms-vscode.Theme-TomorrowKit
    - pavlitsky.yard
    - PeterJausovec.vscode-docker
    - plievone.vscode-template-literal-editor
    - rebornix.ruby
    - redhat.vscode-yaml
    - robertohuertasm.vscode-icons
    - samverschueren.final-newline
    - Shan.code-settings-sync
    - sianglim.slim
    - vscoss.vscode-ansible
    - wholroyd.jinja
  register: result
  become: no
  changed_when: "'is already installed' not in result.stdout"
