---
# Dell XPS 15 9570 tweaks. Source: https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/blob/master/xps-tweaks.sh

- name: Install power management tools
  pacman:
    name: [thermald, tlp, tlp-rdw, powertop, lm-sensors, psensor]

- name: Fix Sleep/Wake Bluetooth Bug
  shell: |
    sed -i '/RESTORE_DEVICE_STATE_ON_STARTUP/s/=.*/=1/' /etc/default/tlp
    systemctl restart tlp
  args:
    warn: false

- name: Uninstall bbswitch
  pacman:
    name: bbswitch
    state: absent

- name: Install bumblebee
  pacman:
    name: bumblebee

- name: Install intel microcode
  pacman:
    name: intel-ucode

- name: Install wifi driver for Killer 1535 card
  shell: |
    m -f /lib/firmware/ath10k/QCA6174/hw3.0/*
    wget -O /lib/firmware/ath10k/QCA6174/hw3.0/board.bin https://github.com/kvalo/ath10k-firmware/blob/master/QCA6174/hw3.0/board.bin?raw=true
    wget -O /lib/firmware/ath10k/QCA6174/hw3.0/board-2.bin https://github.com/kvalo/ath10k-firmware/blob/master/QCA6174/hw3.0/board-2.bin?raw=true
    wget -O /lib/firmware/ath10k/QCA6174/hw3.0/firmware-4.bin https://github.com/kvalo/ath10k-firmware/blob/master/QCA6174/hw3.0/firmware-4.bin_WLAN.RM.2.0-00180-QCARMSWPZ-1?raw=true

- name: Reload systemd configuration
  shell: systemctl daemon-reload

- name: Enable Intel power saving tweaks
  shell: |
    echo "options i915 enable_fbc=1 enable_psr=2 enable_guc=-1 disable_power_well=0 fastboot=1" > /etc/modprobe.d/i915.conf
    update-initramfs -u

- name: Tweak grub defaults
  shell: |
    GRUB_OPTIONS_VAR_NAME="GRUB_CMDLINE_LINUX_DEFAULT"
    GRUB_OPTIONS="quiet acpi_rev_override=1 acpi_osi=Linux scsi_mod.use_blk_mq=1 nouveau.modeset=0 nouveau.runpm=0 mem_sleep_default=deep pcie_port_pm=on"
    GRUB_OPTIONS_VAR="$GRUB_OPTIONS_VAR_NAME=\"$GRUB_OPTIONS\""

    if cat /etc/default/grub | grep "$GRUB_OPTIONS_VAR" &>/dev/null
    then
        echo "Grub is already tweaked!"
    else
        sed -i "s/^$GRUB_OPTIONS_VAR_NAME/# $GRUB_OPTIONS_VAR_NAME/g" /etc/default/grub
        awk '/# '"$GRUB_OPTIONS_VAR_NAME"'/{print;print "'"$GRUB_OPTIONS_VAR_NAME"'=\"'"$GRUB_OPTIONS"'\"";next}1' /etc/default/grub | \
            tee /etc/default/grub &>/dev/null
        update-grub
    fi

- name: Install nVidia drivers
  pacman:
    name: nvidia

- name: Switch to intel card
  shell: prime-select intel 2>/dev/null
