---
# Dell XPS 15 9570 tweaks.
# https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/blob/master/xps-tweaks.sh
# https://wiki.archlinux.org/index.php/Dell_XPS_15_9570

- name: Install power management tools
  pacman:
    name: [thermald, tlp, tlp-rdw, powertop, lm_sensors, psensor]

- name: Get NVIDIA card id
  shell: lspci | awk '/.*NVIDIA.*/ {print $1}'
  register: nvidia_card

- name: Remove NVIDIA from tlp power management
  lineinfile:
    path: /etc/default/tlp
    regexp: '^#?RUNTIME_PM_BLACKLIST=".*"$'
    line: 'RUNTIME_PM_BLACKLIST="{{ nvidia_card.stdout }}"'
    backup: yes
  when: nvidia_card.stdout != ""

- name: Fix Sleep/Wake Bluetooth Bug
  lineinfile:
    path: /etc/default/tlp
    regexp: '^RESTORE_DEVICE_STATE_ON_STARTUP=\d+'
    line: 'RESTORE_DEVICE_STATE_ON_STARTUP=1'
    backup: yes

- name: Uninstall bbswitch
  pacman:
    name: bbswitch
    state: absent

- name: Install bumblebee
  pacman:
    name: bumblebee

- name: Disable power off for NVIDIA
  replace:
    path: /etc/bumblebee/bumblebee.conf
    regexp: '(KernelDriver=nvidia\nPMMethod)=.*'
    replace: '\1=none'
    backup: yes

- name: Enable bumblebee service
  systemd:
    name: bumblebeed.service
    enabled: yes

- name: Install intel microcode
  pacman:
    name: intel-ucode

- name: Install wifi driver for Killer 1535 card
  shell: |
    rm -f /lib/firmware/ath10k/QCA6174/hw3.0/*
    wget -O /lib/firmware/ath10k/QCA6174/hw3.0/board.bin https://github.com/kvalo/ath10k-firmware/blob/master/QCA6174/hw3.0/board.bin?raw=true
    wget -O /lib/firmware/ath10k/QCA6174/hw3.0/board-2.bin https://github.com/kvalo/ath10k-firmware/blob/master/QCA6174/hw3.0/board-2.bin?raw=true
    wget -O /lib/firmware/ath10k/QCA6174/hw3.0/firmware-4.bin https://github.com/kvalo/ath10k-firmware/blob/master/QCA6174/hw3.0/firmware-4.bin_WLAN.RM.2.0-00180-QCARMSWPZ-1?raw=true

- name: Reload systemd configuration
  shell: systemctl daemon-reload

- name: Enable Intel power saving tweaks
  lineinfile:
    path: /etc/modprobe.d/i915.conf
    regexp: '^options i915.*$'
    line: options i915 enable_fbc=1 enable_psr=2 enable_guc=-1 disable_power_well=0 fastboot=1
    create: yes
    backup: yes

- name: Add i915 module
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES=.*$'
    line: 'MODULES=(i915)'
    backup: yes

- name: Regenerate initramfs
  shell: mkinitcpio -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img

- name: Tweak grub default
  lineinfile:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT)=.*$'
    line: '\1="quiet acpi_rev_override=1 acpi_osi=Linux scsi_mod.use_blk_mq=1 nouveau.modeset=0 nouveau.runpm=0 mem_sleep_default=deep pcie_port_pm=on"'
    backrefs: yes
    backup: yes

- name: Update grub
  shell: grub-mkconfig -o /boot/grub/grub.cfg

- name: Install nVidia drivers
  pacman:
    name: nvidia
