---

- name: Install power management tools
  apt:
    name: [thermald, tlp, tlp-rdw, powertop, lm-sensors, psensor]

- name: Fix Sleep/Wake Bluetooth Bug
  shell: |
    sed -i '/RESTORE_DEVICE_STATE_ON_STARTUP/s/=.*/=1/' /etc/default/tlp
    systemctl restart tlp
  args:
    warn: false

- name: Add nVidia drivers repository
  apt_repository:
    repo: ppa:graphics-drivers/ppa

- name: Install nVidia drivers
  apt:
    name: [nvidia-driver-410, nvidia-prime, bbswitch-dkms, pciutils]

- name: Install intel microcode
  apt:
    name: intel-microcode

- name: Install wifi driver
  apt:
    deb: http://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-firmware/linux-firmware_1.175_all.deb

- name: Load wifi drivers
  shell: modprobe -r ath10k_pci && modprobe ath10k_pci

- name: Reload systemd configuration
  shell: systemctl daemon-reload

- name: Enable Intel power saving tweaks
  shell: |
    echo "options i915 enable_fbc=1 enable_psr=2 enable_guc=-1 disable_power_well=0 fastboot=1" > /etc/modprobe.d/i915.conf
    update-initramfs -u

- name: Switch to intel card
  shell: prime-select intel 2>/dev/null

- name: Tweak grub defaults
  shell: |
    GRUB_OPTIONS_VAR_NAME="GRUB_CMDLINE_LINUX_DEFAULT"
    GRUB_OPTIONS="quiet acpi_rev_override=1 acpi_osi=Linux scsi_mod.use_blk_mq=1 nouveau.modeset=0 nouveau.runpm=0 mem_sleep_default=deep"
    GRUB_OPTIONS_VAR="$GRUB_OPTIONS_VAR_NAME=\"$GRUB_OPTIONS\""

    if cat /etc/default/grub | grep "$GRUB_OPTIONS_VAR" &>/dev/null
    then
        echo "Grub is already tweaked!"
    else
        sed -i "s/^$GRUB_OPTIONS_VAR_NAME/# $GRUB_OPTIONS_VAR_NAME/g" /etc/default/grub
        awk '/# '"$GRUB_OPTIONS_VAR_NAME"'/{print;print "'"$GRUB_OPTIONS_VAR_NAME"'=\"'"$GRUB_OPTIONS"'\"";next}1' /etc/default/grub | \
            tee /etc/default/grub &>/dev/null
        update-grub
    fi
