---

- name: Install stow
  pacman:
    name: stow
    state: latest

- name: Clone stow files
  git:
    repo: "{{ vault_stow_files }}"
    dest: "{{ stow_files_dest }}"
  become: no

- name: Symlink configs
  command: "stow -d {{ stow_files_dest }} -S {{ item }}"
  with_lines: cat {{ stowed_configs }}
  become: no
