---

- name: Install stow
  apt:
    name: stow
    state: latest

- name: Symlink configs
  command: "stow -d {{ dotfiles }} -S {{ item }}"
  with_lines: "cat {{ dotfiles }}/stow.txt"
  ignore_errors: yes
  become: no
