---

- name: Check if sdkman is installed
  stat:
    path: "{{ sdk_home }}"
  register: sdk

- name: Installing sdk manager
  shell: "curl -s https://get.sdkman.io | bash"
  args:
    creates: "{{ sdk_home }}"
    warn: false
  when: not sdk.stat.exists

- name: Update sdkman
  shell: "{{ init_sdkman }} && sdk selfupdate"
  register: sdk_update
  changed_when: "'No update available at this time' not in sdk_update.stdout"

- name: Install sdks
  shell: "{{ init_sdkman }} && sdk install {{ item }}"
  with_items:
    - "{{ sdks }}"
  register: sdk_installs
  changed_when: "'is already installed' not in sdk_installs.stdout" 

- name: Update sdks
  shell: "{{ init_sdkman }} && sdk upgrade {{ item }}"
  with_items:
    - "{{ sdks }}"
  register: sdk_updates
  changed_when: "'is up-to-date' not in sdk_updates.stdout"
