---

- name: Install zsh
  apt:
    name: zsh
  become: yes

- name: Clone oh-my-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "{{ omzsh_dir }}"
    accept_hostkey: yes

- name: Check if omzsh is installed
  stat:
    path: "{{ omzsh_dir }}"
  register: omzsh

- name: Install oh-my-zsh
  shell: "{{ omzsh_dir }}/tools/install.sh"
  when: not omzsh.stat.exists

- name: Clone powerlevel10k theme
  git:
    repo: "{{ github }}romkatv/powerlevel10k.git"
    dest: "{{ omzsh_themes_dir }}/powerlevel10k"
    accept_hostkey: yes

- name: Cloning custom plugins
  git:
    repo: "https://github.com/{{ item.value }}/{{ item.key }}.git"
    dest: "{{ omzsh_plugins_dir }}/{{ item.key }}"
    accept_hostkey: yes
  with_dict:
    "{{ omzsh_plugins }}"

- name: Clone base16 shell themes
  git:
    repo: "https://github.com/chriskempson/base16-shell.git"
    dest: "{{ user.home }}/.config/base16-shell"
    accept_hostkey: yes

- name: Check for original .zshrc
  stat:
    path: "{{ user.home }}/.zshrc"
  register: stat_zshrc

- name: Back up .zshrc file
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: ~/.zshrc.bak
  when: stat_zshrc.stat.exists

- name: Create .zshrc from template
  template:
    src: .zshrc.j2
    dest: "{{ user.home }}/.zshrc"

- name: Set zsh as default shell
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh
  become: yes
  