---

- name: Install Git
  pacman:
    name: git
    state: latest

- name: Install lazygit
  aur:
    name: lazygit
    user: "{{ user.name }}"

- name: Install diff-so-fancy
  yarn:
    name: diff-so-fancy
    global: yes
    state: latest
