---

- name: Clone node version manager
  git:
    repo: "{{ github }}creationix/nvm.git"
    dest: "{{ nvm_home }}"
    accept_hostkey: yes
  become: no

- name: Set nvm to latest version
  shell: "git checkout `git describe --abbrev=0 --tags --match \"v[0-9]*\" $(git rev-list --tags --max-count=1)`"
  args:
    chdir: "{{ nvm_home }}"
  become: no


- name: Install latest node version
  shell: "{{ init_nvm }} && nvm install node"
  become: no

- name: Install yarn
  pacman:
    name: yarn
    state: latest

- name: Install latest global npm packages
  yarn:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items:
    - nodemon
    - tslint
    - eslint
  become: no
