---

- name: Perform upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: Install various tools
  apt:
    name:
      - build-essential
      - htop
      - nfs-kernel-server
      - qbittorrent
      - rsync
      - openssh-server
      - curl
    state: latest
