---

- name: Perform upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install essential libs
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - base-devel
    - expect
    - go
    - python
    - python-pip
    - ruby
    - npm
    - yarn

- name: Install common software
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - jq
    - httpie
    - guake
    - htop
    - cifs-utils
    - samba
    - ufw
    - tlp
    - ecryptfs-utils
    - bat
    - ncdu

- name: Install additional aur software
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - direnv
    - clipit
    - prettyping
  tags:
    - aur

- name: Install latest global npm packages
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items:
    - nodemon
    - tslint
    - eslint

- name: Create AUR directory
  file:
    path: "/home/{{ user.name }}/aur"
    state: directory
  become: no
  tags:
    - aur
