---

- name: Perform upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install dev dependencies
  pacman:
    name:
      - git
      - base-devel
      - python
    state: latest

- name: Install various tools
  pacman:
    name:
      - jq
      - httpie
      - guake
      - htop
      - cifs-utils
      - ufw
      - ecryptfs-utils
      - bat
      - ncdu
      - tldr
      - python-pip
      - expect
      - openvpn
      - networkmanager-openvpn
      - prettyping
    state: latest

- name: Install additional aur software
  aur:
    name:
      - direnv
      - albert
    use: makepkg
    skip_installed: yes
  become: no
