---

- name: Perform upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install essential libs
  pacman:
    name: [
      base-devel,
      expect,
      go,
      python,
      python-pip,
      ruby
    ]
    state: latest

- name: Install common software
  pacman:
    name: [
      jq,
      httpie,
      guake,
      htop,
      cifs-utils,
      samba,
      ufw,
      tlp,
      ecryptfs-utils,
      bat,
      ncdu,
      gpaste
    ]
    state: latest

- name: Create AUR directory
  file:
    path: "/home/{{ user.name }}/aur"
    state: directory
  become: no
  tags:
    - aur

- name: Install additional aur software
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - direnv
    - prettyping
    - albert
  tags:
    - aur
