---

- name: Perform upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install essential libs
  pacman:
    name: [
      base-devel,
      python,
      python-pip
    ]
    state: latest

- name: Install common software
  pacman:
    name: [
      jq,
      httpie,
      tilda,
      htop,
      cifs-utils,
      samba,
      ufw,
      ecryptfs-utils,
      bat,
      ncdu,
    ]
    state: latest

- name: Create AUR directory
  file:
    path: "{{ aur_dir }}"
    state: directory
  become: no

- name: Install additional aur software
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
    dir: "{{ aur_dir }}"
  with_items:
    - direnv
    - prettyping
    - albert
