---

- name: Install Docker
  pacman:
    name: [docker, docker-compose]
    state: latest 

- name: Add user to docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    append: yes

- name: Enable docker
  systemd:
    name: docker
    enabled: yes
