---

- name: create .ssh dir if it doesn't exist
  file:
    path: ~/.ssh
    state: directory
  become: no

- name: Copy ssh keys
  copy:
    src: "{{ item }}"
    dest: ~/.ssh
    mode: 0600
  become: no
  with_items:
    - "{{ ssh_keys }}"

- name: Import gpg key pair
  command: gpg --import "{{ item }}"
  register: command_result
  failed_when: "'processed: 1' not in command_result.stderr"
  become: no
  with_items:
    - "{{ gpg_keys }}"
